
# Offers IPC using alacritty msg
# ipc_socket = true | false

# Sets enviroment variable for process spawned by alacritty
[env]
TERM = "xterm-256color"
 FOO = "bar"


[window]
# dimensions = { columns = 20, lines = 10 }
# position = "None" | { x = <integer>, y = <integer> }

padding = {x = 15, y = 15}

# dynamic_padding = true | false

# decorations = "Full" | "None" | "Transparent" | "Buttonless"

opacity = 0.9

[font.normal]
family = "Firacode Nerd Font"
style = "Regular"

[general]

live_config_reload = true

# [shell]
# program = "/bin/bash"
# args = ["-l"]

# Starts the shell in specified directory
working_directory = "None"
# Imports additional config files
import = [ "~/.config/alacritty/themes/aura-theme.toml" ]

[terminal]

# sets the default shell program
shell = "/bin/fish"

# [colors]
# draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "0x444b6a"
# blue = "0x7da6ff"
# cyan = "0x0db9d7"
# green = "0xb9f27c"
# magenta = "0xbb9af7"
# red = "0xff7a93"
# white = "0xacb0d0"
# yellow = "0xff9e64"

# [colors.normal]
# black = "0x32344a"
# blue = "0x7aa2f7"
# cyan = "0x449dab"
# green = "0x9ece6a"
# magenta = "0xad8ee6"
# red = "0xf7768e"
# white = "0x787c99"
# yellow = "0xe0af68"

# [colors.primary]
# background = "0x1a1b26"
# foreground = "0xa9b1d6"

# [env]
# TERM = "xterm-256color"

[font]
size = 16.0

# [font.bold]
# family = "Source Code Pro"
# style = "Bold"

# [font.bold_italic]
# family = "Source Code Pro"
# style = "Bold Italic"

# [font.italic]
# family = "Source Code Pro"
# style = "Italic"

# [font.normal]
# family = "Source Code Pro"
# style = "Regular"

# [font.offset]
# x = 0
# y = 1

# [scrolling]
# history = 5000

# [window]
# dynamic_padding = false
# opacity = 0.4
# title = "Alacritty"

# [window.class]
# general = "Alacritty"
# instance = "Alacritty"

# [window.padding]
# x = 6
# y = 6
