# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# ~/.config/starship.toml

# Use custom format
format = '''

[┌$username](bold green)$directory$package$git_branch
[└─>](bold green) '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[username]
show_always = true
style_root = "bold red"
style_user = "bold purple"
format = '[@$user ]($style)'
disabled = false

# Set 'foo' as custom color palette
#palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = '\[[$symbol$branch]($style)\]'
