wallpaper {
    monitor = 
    path = /home/arctan/dotfiles/Wallpapers/vibrant-gate.png
    fit_mode = cover
}
# preload = /home/arctan/dotfiles/Wallpapers/vibrant-gate.png
# wallpaper = eDP-1,/home/arctan/dotfiles/Wallpapers/vibrant-gate.png
